### ISSUE TITLE
Code General Failure

### ISSUE THREAD

**Issue by IntvPrime** [1ucasvb/pokey2midi#2]
Using Python 3.9.4 (tags/v3.9.4:1f2e308, Apr  4 2021, 13:27:16) [MSC v.1928 64 bit (AMD64)] on win32.

pokey2midi.py samples\sap\An_Anthem_for_Winterchip.sap

====================[ POKEY2MIDI v0.85 ]====================
Opening "samples\sap\An_Anthem_for_Winterchip.sap"
None
ERROR
Incorrect input format.

I commented-out lines 676,677,678 to skip the error checking, and then get this result:

====================[ POKEY2MIDI v0.85 ]====================
Opening "samples\sap\An_Anthem_for_Winterchip.sap"
None
Reading POKEY data...
Traceback (most recent call last):
  File "D:\temp\greg_music_archive-1.0\pokey2midi-master\pokey2midi.py", line 1058, in <module>
    converter.convert(input, output)
  File "D:\temp\greg_music_archive-1.0\pokey2midi-master\pokey2midi.py", line 689, in convert
    l = fin.readline()
  File "C:\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 246: character maps to <undefined>

I am unsure what might be happening in this case, please advise (Python version issue)?

Thanks.

**Comment by 1ucasvb** [comment]
Hi, thanks for interest and the report!

What went wrong here is that you cannot run POKEY2MIDI directly on a binary SAP file. [As per the instructions](https://github.com/1ucasvb/pokey2midi), you first need to use `asapscan` to generate a text dump of the POKEY registers. 

The error here is that the Python FILE.readlines() function found a binary non-printable character in the input file. POKEY2MIDI is not a decoder of SAP files (which requires emulating the Atari computer and POKEY chip), it just interprets the generated audio data (the POKEY registers) to translate it to notes.

For this song you won't need to run asapscan. You can find the bzipped dump for "An Anthem for Winterchip" on the "dump" folder, which you can use to try out the code and the various settings. If you run POKEY2MIDI on "/dump/An_Anthem_for_Winterchip_(subsong 0).txt.bz2" it should work.
