### ISSUE TITLE
error whilte try converting but i got error

### ISSUE THREAD

**Issue by james111731** [1ucasvb/pokey2midi#3]
so I have a problem with pokey2midi I try to use the black lamp.sap but I got that error any idea?
![image](https://user-images.githubusercontent.com/60959799/217663624-783306b2-e317-48e8-9224-07a4c424e169.png)

**Comment by 1ucasvb** [comment]
Hi! Thanks for using POKEY2MIDI. :)

I have not included any `asapscan` binaries in my GitHub repository, so the `create_samples.py` script won't run out of the box.

You need to download the appropriate binary for your OS from: https://asap.sourceforge.net/
As you seem to be on Windows, grab it from the latest Windows release: https://sourceforge.net/projects/asap/files/asap/5.3.0/asap-5.3.0-win32.zip/download

You can then follow the [instructions in the readme](https://github.com/1ucasvb/pokey2midi#instructions), but here's how the basic process goes. Place `asapscan.exe` in the same folder (for simplicity) as `Black_Lamp.sap`, open a command prompt there, and type:
    asapscan -d Black_Lamp.sap > Black_Lamp.txt

This will make `asapscan` dump the POKEY registers into a text file `Black_Lamp.txt`, and you then run POKEY2MIDI on that text file.

If you prefer to let the `create_samples.py` do the job for you, as you are doing at the moment, then you have two options:
* Create a `bin` folder in the same location as `pokey2midi.py`, and put `asapscan.exe` inside this `bin` folder. This is where `create_samples.py` is currently looking for the program, and this is why you got the error. That file doesn't exist!
* Or, open `create_samples.py` and put the full location of `asapscan.exe` in there. Replace:
    asapscan_path = os.path.join("..","bin","asapscan")
    With
    asapscan_path = "(full path to asapscan.exe here)"

I recommend you don't use `create_samples.py` and just [look at the readme](https://github.com/1ucasvb/pokey2midi) to understand better how to use the script. You are only missing `asapscan.exe`, so it should be easy once you have it set up.

Alternatively, you can try using the pre-converted MIDI version from Gades' conversion of the entire ASMA. See here: https://github.com/1ucasvb/pokey2midi#atari-sap-music-archive-asma-conversion-to-midi

I hope this clears things up. Let me know if it all works out or not. Cheers!
